### ISSUE TITLE
/__webpack_hmr 404

### ISSUE THREAD

**Issue by avelino** [codercom/code-server#141]
```
"GET /__webpack_hmr HTTP/1.1" 404 152 "https://...../" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36"
```

- `code-server` version: master branch
- OS Version: ubuntu

#### Steps to Reproduce

1. open coder ide

**Comment by kylecarbs** [comment]
Will be fixed!

**Comment by kylecarbs** [comment]
#149 shouldn't have fix this. This is related to a build issue w/ webpack.

**Comment by xuemind** [comment]
Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-1030-azure x86_64)
code-server-1.31.1-100-linux-x64
**Request**
```
GET https://<code-server-ip>:8443/__webpack_hmr
```
**Response Code: 404**
``` html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /__webpack_hmr</pre>
</body>
</html>
```

**Comment by avelino** [comment]
Check masteR branch, not generate release

**Comment by dirkcgrunwald** [comment]
I wanted to clarify your comment - are you saying that the fix is in the master branch but not in e.g. the 1.32.0-245 release or do you mean earlier releases?

I'm trying to proxy code-server in JupyterHub (data science tool). I'm still getting 
```
404 GET /__webpack_hmr (172.17.0.1) 1.62ms referer=http://localhost:7777/codeserver/
```
using the 1.32.0-245 release binaries. I'm building my environment as in https://gist.github.com/dirkcgrunwald/d3d5669e291e8249f5b4f6ad8b6c1f46

I haven't tried building from source because my other tools need node 11.11.0

**Comment by si458** [comment]
i have pulled the latest image from https://hub.docker.com/r/codercom/code-server
(March 13, 2019 07:36 PM) and im still getting the 404 error ?

sample stack file
```
version: '2'
services:
  codeserver:
    image: codercom/code-server:latest
    ports:
      - 8443
    volumes:
      - codeserver:/root/project
volumes:
  codeserver:
    driver: local
```

**Comment by si458** [comment]
i have pulled the latest image again this morning from https://hub.docker.com/r/codercom/code-server (March 15, 2019 05:19 AM) and im still getting the 404 error ?
`Firefox can't establish a connection to the server at https://192.168.168.77:32770/__webpack_hmr.`
i only use a docker-compose file, nothing special
```
version: '2'
services:
  codeserver:
    image: codercom/code-server:latest
    ports:
      - 8443
    volumes:
      - codeserver:/root/project
    command: --allow-http --no-auth
volumes:
  codeserver:
    driver: local
```
