### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by haoteng10** [codercom/code-server#453]
- `code-server` version: 1.691-vsc1.33.0
- OS Version: Ubuntu 18.04 LTS Minimal, Google Cloud

## Description

When I tried to run the code-server command, it gives me this error:

WARN  Uncaught Exception:  Error: Unexpected end of JSON input

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at pfs_1.readFile.then.contents (/home/travis/build/codercom/code-server/packages/server/build/bootstrap-fork.js.gz:76703:45)
    at <anonymous>
    at Timeout.setTimeout [as _onTimeout] (/home/travis/build/codercom/code-server/packages/server/build/bootstrap-fork.js.gz:53086:31)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

Also, when I tried to connect the website ignoring the error, I received the error `x.x.x.x refused to connect`. (Okay. This is a different issue. I need to specify the specific IP address for the code-server to run on instead of 0.0.0.0)

## Steps to Reproduce

1. Extract the code-server and put it in bin.
1. Run command `sudo code-server -p 80`

**Comment by kylecarbs** [comment]
That error likely isn't causing the `refused to connect`.

**Comment by haoteng10** [comment]
@kylecarbs The syntax error should be ignored?

**Comment by axelaxelsson** [comment]
I get same error
 
code-server v1.604-vsc1.32.0
OS version: Debian GNU/Linux 9.8 (stretch)

**Comment by malikowy** [comment]
the same issue, using AWS EC2

ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20190212 (ami-05af84768964d3dc0)

**Comment by nlighteneddesign** [comment]
I am getting a similar error in my docker logs:

```SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at pfs_1.readFile.then.contents (/src/packages/server/build/bootstrap-fork.js.gz:95779:45)
    at <anonymous>
    at Timeout.setTimeout [as _onTimeout] (/src/packages/server/build/bootstrap-fork.js.gz:71026:31)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
INFO  WebSocket closed / {"client":2,"code":1001}
```

I am trying to run this using docker-compose. The editor loads for me on the port specified, but the project files are not visible.

```
  vscode:
    container_name: vscode
    restart: unless-stopped
    image: codercom/code-server
    user: root
    ports:
      - "8443:8443"
    volumes:
      - "/srv/docker/hass-config:/home/coder/project"
    command: "code-server --allow-http --no-auth"
```
